contact_links:
  - name: Ask a question
    url: https://github.com/Eonasdan/tempus-dominus/discussions/new
    about: Ask and discuss questions with other community members
  - name: Join the discord
    url: https://discord.gg/BHS9jw9YPf
