name: Pull Request
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yaml@v1
    secrets: inherit
